### ISSUE TITLE
请问这个要怎么用？

### ISSUE THREAD

**Issue by LouLamSan** [MapleRen/MapleStoryM-language#1]
请问这个在ios里面的shadowrocket怎么使用

**Comment by MapleRen** [comment]
在小火箭的“配置”页面点击右上角“+”，下载并使用对应配置即可
[基础汉化](https://raw.githubusercontent.com/MapleRen/MapleStoryM-language/master/Kor/Shadowrocket/kor_base.conf)
[进阶汉化](https://raw.githubusercontent.com/MapleRen/MapleStoryM-language/master/Kor/Shadowrocket/kor_pro.conf)
