### ISSUE TITLE
Surge使用

### ISSUE THREAD

**Issue by xaver985** [MapleRen/MapleStoryM-language#13]
你好，Surge能否使用国际服解锁脚本？

**Comment by MapleRen** [comment]
[https://raw.githubusercontent.com/MapleRen/MapleStoryM-language/master/Global/Surge/msm_unblock.sgmodule](url)
可以的，已添加以上模块，由于我没有Surge，所以不确定可不可行，你试试这个

**Comment by xaver985** [comment]
测试后发现Surge进不去游戏，游戏中提示ToyError 10010
Surge提示script failed, abort
![B156AB7A-7904-4F19-B13F-456CBF5191D8](https://user-images.githubusercontent.com/32983060/105120116-9a379080-5b0c-11eb-8a35-07597e605d62.jpeg)

**Comment by xaver985** [comment]
QuantumultX测试可以进入游戏

**Comment by MapleRen** [comment]
应该是$done方法的问题，已修改

**Comment by xaver985** [comment]
谢谢，已经可以了
