### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by sqzhang-jeremy** [MapleRen/MapleStoryM-language#4]
Hey, thank u for u awesome work in translating MapleStoryM into Chinese version! I have already experienced it, that's cool. But I don't know whether there has an english patch of MapleStoryM Korea Server. I hope that I could  play in english version of Korea Server. Thanks!

**Comment by Scholar-m** [comment]
Hello, regarding this aspect, if you do production, it will greatly increase the workload. We have no plan in that regard.

**Comment by sqzhang-jeremy** [comment]
fine:( I have to admit that that is a big work, thank u for u awesome work for us.
